//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from G:/Dev/Carbon/Carbon/Parser/Grammar\Carbon.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CarbonParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface ICarbonVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.carbon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCarbon([NotNull] CarbonParser.CarbonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.symbol_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSymbol_id([NotNull] CarbonParser.Symbol_idContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.preproc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreproc([NotNull] CarbonParser.PreprocContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.pp_import"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPp_import([NotNull] CarbonParser.Pp_importContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.pp_define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPp_define([NotNull] CarbonParser.Pp_defineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] CarbonParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] CarbonParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.classExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassExpr([NotNull] CarbonParser.ClassExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.interfaceExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceExpr([NotNull] CarbonParser.InterfaceExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.inheritListExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInheritListExpr([NotNull] CarbonParser.InheritListExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.procCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcCallExpr([NotNull] CarbonParser.ProcCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.bodyExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBodyExpr([NotNull] CarbonParser.BodyExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.groupExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupExpr([NotNull] CarbonParser.GroupExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.fncGroupExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFncGroupExpr([NotNull] CarbonParser.FncGroupExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.forGroupExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForGroupExpr([NotNull] CarbonParser.ForGroupExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.whileGroupExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileGroupExpr([NotNull] CarbonParser.WhileGroupExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.indexExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexExpr([NotNull] CarbonParser.IndexExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.gotoExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGotoExpr([NotNull] CarbonParser.GotoExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.varDeclExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDeclExpr([NotNull] CarbonParser.VarDeclExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.propDefExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropDefExpr([NotNull] CarbonParser.PropDefExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.propGetExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropGetExpr([NotNull] CarbonParser.PropGetExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.propSetExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropSetExpr([NotNull] CarbonParser.PropSetExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.fncDeclExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFncDeclExpr([NotNull] CarbonParser.FncDeclExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.ctrlCndExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCtrlCndExpr([NotNull] CarbonParser.CtrlCndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.ctrlWhileExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCtrlWhileExpr([NotNull] CarbonParser.CtrlWhileExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.ctrlForExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCtrlForExpr([NotNull] CarbonParser.CtrlForExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.setExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetExpr([NotNull] CarbonParser.SetExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.mathUnExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMathUnExpr([NotNull] CarbonParser.MathUnExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.mathBinExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMathBinExpr([NotNull] CarbonParser.MathBinExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.compValExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompValExpr([NotNull] CarbonParser.CompValExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.logicBinExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicBinExpr([NotNull] CarbonParser.LogicBinExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.logicUnExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicUnExpr([NotNull] CarbonParser.LogicUnExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.valueExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueExpr([NotNull] CarbonParser.ValueExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.mathUnLeftExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMathUnLeftExpr([NotNull] CarbonParser.MathUnLeftExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.mathUnRightExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMathUnRightExpr([NotNull] CarbonParser.MathUnRightExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.boolValsExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolValsExpr([NotNull] CarbonParser.BoolValsExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CarbonParser.ctrlKwExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCtrlKwExpr([NotNull] CarbonParser.CtrlKwExprContext context);
}
