//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from G:/Dev/Carbon/Carbon/Parser/Grammar\Carbon.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICarbonListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class CarbonBaseListener : ICarbonListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.carbon"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCarbon([NotNull] CarbonParser.CarbonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.carbon"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCarbon([NotNull] CarbonParser.CarbonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.symbol_id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSymbol_id([NotNull] CarbonParser.Symbol_idContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.symbol_id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSymbol_id([NotNull] CarbonParser.Symbol_idContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.preproc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreproc([NotNull] CarbonParser.PreprocContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.preproc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreproc([NotNull] CarbonParser.PreprocContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.pp_import"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPp_import([NotNull] CarbonParser.Pp_importContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.pp_import"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPp_import([NotNull] CarbonParser.Pp_importContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.pp_define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPp_define([NotNull] CarbonParser.Pp_defineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.pp_define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPp_define([NotNull] CarbonParser.Pp_defineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] CarbonParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] CarbonParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] CarbonParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] CarbonParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.classExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassExpr([NotNull] CarbonParser.ClassExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.classExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassExpr([NotNull] CarbonParser.ClassExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.interfaceExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceExpr([NotNull] CarbonParser.InterfaceExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.interfaceExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceExpr([NotNull] CarbonParser.InterfaceExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.inheritListExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInheritListExpr([NotNull] CarbonParser.InheritListExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.inheritListExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInheritListExpr([NotNull] CarbonParser.InheritListExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.procCallExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcCallExpr([NotNull] CarbonParser.ProcCallExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.procCallExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcCallExpr([NotNull] CarbonParser.ProcCallExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.bodyExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBodyExpr([NotNull] CarbonParser.BodyExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.bodyExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBodyExpr([NotNull] CarbonParser.BodyExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.groupExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroupExpr([NotNull] CarbonParser.GroupExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.groupExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroupExpr([NotNull] CarbonParser.GroupExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.fncGroupExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFncGroupExpr([NotNull] CarbonParser.FncGroupExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.fncGroupExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFncGroupExpr([NotNull] CarbonParser.FncGroupExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.forGroupExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForGroupExpr([NotNull] CarbonParser.ForGroupExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.forGroupExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForGroupExpr([NotNull] CarbonParser.ForGroupExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.whileGroupExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileGroupExpr([NotNull] CarbonParser.WhileGroupExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.whileGroupExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileGroupExpr([NotNull] CarbonParser.WhileGroupExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.indexExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexExpr([NotNull] CarbonParser.IndexExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.indexExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexExpr([NotNull] CarbonParser.IndexExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.gotoExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGotoExpr([NotNull] CarbonParser.GotoExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.gotoExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGotoExpr([NotNull] CarbonParser.GotoExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.varDeclExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDeclExpr([NotNull] CarbonParser.VarDeclExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.varDeclExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDeclExpr([NotNull] CarbonParser.VarDeclExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.propDefExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropDefExpr([NotNull] CarbonParser.PropDefExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.propDefExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropDefExpr([NotNull] CarbonParser.PropDefExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.propGetExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropGetExpr([NotNull] CarbonParser.PropGetExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.propGetExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropGetExpr([NotNull] CarbonParser.PropGetExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.propSetExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropSetExpr([NotNull] CarbonParser.PropSetExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.propSetExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropSetExpr([NotNull] CarbonParser.PropSetExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.fncDeclExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFncDeclExpr([NotNull] CarbonParser.FncDeclExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.fncDeclExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFncDeclExpr([NotNull] CarbonParser.FncDeclExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.ctrlCndExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCtrlCndExpr([NotNull] CarbonParser.CtrlCndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.ctrlCndExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCtrlCndExpr([NotNull] CarbonParser.CtrlCndExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.ctrlWhileExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCtrlWhileExpr([NotNull] CarbonParser.CtrlWhileExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.ctrlWhileExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCtrlWhileExpr([NotNull] CarbonParser.CtrlWhileExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.ctrlForExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCtrlForExpr([NotNull] CarbonParser.CtrlForExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.ctrlForExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCtrlForExpr([NotNull] CarbonParser.CtrlForExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.setExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetExpr([NotNull] CarbonParser.SetExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.setExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetExpr([NotNull] CarbonParser.SetExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.mathUnExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMathUnExpr([NotNull] CarbonParser.MathUnExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.mathUnExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMathUnExpr([NotNull] CarbonParser.MathUnExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.mathBinExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMathBinExpr([NotNull] CarbonParser.MathBinExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.mathBinExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMathBinExpr([NotNull] CarbonParser.MathBinExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.compValExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompValExpr([NotNull] CarbonParser.CompValExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.compValExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompValExpr([NotNull] CarbonParser.CompValExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.logicBinExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicBinExpr([NotNull] CarbonParser.LogicBinExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.logicBinExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicBinExpr([NotNull] CarbonParser.LogicBinExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.logicUnExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicUnExpr([NotNull] CarbonParser.LogicUnExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.logicUnExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicUnExpr([NotNull] CarbonParser.LogicUnExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.valueExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueExpr([NotNull] CarbonParser.ValueExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.valueExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueExpr([NotNull] CarbonParser.ValueExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.mathUnLeftExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMathUnLeftExpr([NotNull] CarbonParser.MathUnLeftExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.mathUnLeftExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMathUnLeftExpr([NotNull] CarbonParser.MathUnLeftExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.mathUnRightExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMathUnRightExpr([NotNull] CarbonParser.MathUnRightExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.mathUnRightExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMathUnRightExpr([NotNull] CarbonParser.MathUnRightExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.boolValsExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolValsExpr([NotNull] CarbonParser.BoolValsExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.boolValsExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolValsExpr([NotNull] CarbonParser.BoolValsExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.ctrlKwExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCtrlKwExpr([NotNull] CarbonParser.CtrlKwExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.ctrlKwExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCtrlKwExpr([NotNull] CarbonParser.CtrlKwExprContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
