//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from G:/Dev/Carbon/Carbon/Parser/Grammar\Carbon.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CarbonParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface ICarbonListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.carbon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCarbon([NotNull] CarbonParser.CarbonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.carbon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCarbon([NotNull] CarbonParser.CarbonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.symbol_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSymbol_id([NotNull] CarbonParser.Symbol_idContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.symbol_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSymbol_id([NotNull] CarbonParser.Symbol_idContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.preproc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPreproc([NotNull] CarbonParser.PreprocContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.preproc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPreproc([NotNull] CarbonParser.PreprocContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.pp_import"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPp_import([NotNull] CarbonParser.Pp_importContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.pp_import"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPp_import([NotNull] CarbonParser.Pp_importContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.pp_define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPp_define([NotNull] CarbonParser.Pp_defineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.pp_define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPp_define([NotNull] CarbonParser.Pp_defineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] CarbonParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] CarbonParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] CarbonParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] CarbonParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.classExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassExpr([NotNull] CarbonParser.ClassExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.classExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassExpr([NotNull] CarbonParser.ClassExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.interfaceExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceExpr([NotNull] CarbonParser.InterfaceExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.interfaceExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceExpr([NotNull] CarbonParser.InterfaceExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.inheritListExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInheritListExpr([NotNull] CarbonParser.InheritListExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.inheritListExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInheritListExpr([NotNull] CarbonParser.InheritListExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.procCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcCallExpr([NotNull] CarbonParser.ProcCallExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.procCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcCallExpr([NotNull] CarbonParser.ProcCallExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.bodyExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBodyExpr([NotNull] CarbonParser.BodyExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.bodyExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBodyExpr([NotNull] CarbonParser.BodyExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.groupExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupExpr([NotNull] CarbonParser.GroupExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.groupExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupExpr([NotNull] CarbonParser.GroupExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.fncGroupExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFncGroupExpr([NotNull] CarbonParser.FncGroupExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.fncGroupExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFncGroupExpr([NotNull] CarbonParser.FncGroupExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.forGroupExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForGroupExpr([NotNull] CarbonParser.ForGroupExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.forGroupExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForGroupExpr([NotNull] CarbonParser.ForGroupExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.whileGroupExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileGroupExpr([NotNull] CarbonParser.WhileGroupExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.whileGroupExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileGroupExpr([NotNull] CarbonParser.WhileGroupExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.indexExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexExpr([NotNull] CarbonParser.IndexExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.indexExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexExpr([NotNull] CarbonParser.IndexExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.gotoExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGotoExpr([NotNull] CarbonParser.GotoExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.gotoExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGotoExpr([NotNull] CarbonParser.GotoExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.varDeclExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDeclExpr([NotNull] CarbonParser.VarDeclExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.varDeclExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDeclExpr([NotNull] CarbonParser.VarDeclExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.propDefExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropDefExpr([NotNull] CarbonParser.PropDefExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.propDefExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropDefExpr([NotNull] CarbonParser.PropDefExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.propGetExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropGetExpr([NotNull] CarbonParser.PropGetExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.propGetExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropGetExpr([NotNull] CarbonParser.PropGetExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.propSetExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropSetExpr([NotNull] CarbonParser.PropSetExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.propSetExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropSetExpr([NotNull] CarbonParser.PropSetExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.fncDeclExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFncDeclExpr([NotNull] CarbonParser.FncDeclExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.fncDeclExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFncDeclExpr([NotNull] CarbonParser.FncDeclExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.ctrlCndExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCtrlCndExpr([NotNull] CarbonParser.CtrlCndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.ctrlCndExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCtrlCndExpr([NotNull] CarbonParser.CtrlCndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.ctrlWhileExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCtrlWhileExpr([NotNull] CarbonParser.CtrlWhileExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.ctrlWhileExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCtrlWhileExpr([NotNull] CarbonParser.CtrlWhileExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.ctrlForExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCtrlForExpr([NotNull] CarbonParser.CtrlForExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.ctrlForExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCtrlForExpr([NotNull] CarbonParser.CtrlForExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.setExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetExpr([NotNull] CarbonParser.SetExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.setExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetExpr([NotNull] CarbonParser.SetExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.mathUnExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMathUnExpr([NotNull] CarbonParser.MathUnExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.mathUnExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMathUnExpr([NotNull] CarbonParser.MathUnExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.mathBinExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMathBinExpr([NotNull] CarbonParser.MathBinExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.mathBinExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMathBinExpr([NotNull] CarbonParser.MathBinExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.compValExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompValExpr([NotNull] CarbonParser.CompValExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.compValExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompValExpr([NotNull] CarbonParser.CompValExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.logicBinExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicBinExpr([NotNull] CarbonParser.LogicBinExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.logicBinExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicBinExpr([NotNull] CarbonParser.LogicBinExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.logicUnExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicUnExpr([NotNull] CarbonParser.LogicUnExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.logicUnExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicUnExpr([NotNull] CarbonParser.LogicUnExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.valueExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueExpr([NotNull] CarbonParser.ValueExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.valueExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueExpr([NotNull] CarbonParser.ValueExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.mathUnLeftExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMathUnLeftExpr([NotNull] CarbonParser.MathUnLeftExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.mathUnLeftExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMathUnLeftExpr([NotNull] CarbonParser.MathUnLeftExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.mathUnRightExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMathUnRightExpr([NotNull] CarbonParser.MathUnRightExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.mathUnRightExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMathUnRightExpr([NotNull] CarbonParser.MathUnRightExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.boolValsExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolValsExpr([NotNull] CarbonParser.BoolValsExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.boolValsExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolValsExpr([NotNull] CarbonParser.BoolValsExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CarbonParser.ctrlKwExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCtrlKwExpr([NotNull] CarbonParser.CtrlKwExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CarbonParser.ctrlKwExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCtrlKwExpr([NotNull] CarbonParser.CtrlKwExprContext context);
}
